tasks:
  - init: |
      date
      docker-compose build web
      date
      docker-compose pull postgres redis
      date

    command: |
      date
      docker-compose up -d web postgres redis
      date

github:
  prebuilds:
    master: true
    branches: true
