tasks:
  - init: |
      time docker-compose build web

    command: |
      time docker-compose up -d web postgres redis

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
