version: "3.7"
services:
  postgres:
    image: postgres:10.1
    ports:
      - "5432"

  redis:
    image: redis
    ports:
      - "6379"

  web:
    build: .
    command: ["sleep", "300"]
    depends_on:
      - postgres
      - redis
